services:
  - type: web
    name: aadhaar-ocr-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    region: oregon
    runtime: python

    aptBuild:
      apt_packages:
        - tesseract-ocr
        - tesseract-ocr-eng
        - libtesseract-dev
