services:
  - type: web
    name: aadhaar-ocr-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    region: singapore
    autoDeploy: true
