services:
  - type: web
    name: aadhaar-ocr-api
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      PYTHON_VERSION: 3.8
    build:
      packages:
        - tesseract-ocr
        - libtesseract-dev
